import { SupportedLanguage } from './i18n';

export interface GuideChapter {
  id: string;
  icon: string;
  title: string;
  subtitle: string;
  badge?: string;
  paragraphs: string[];
  bulletPoints?: { title: string; desc: string }[];
  tip?: string;
}

export const GUIDE_CHAPTERS: Record<SupportedLanguage, GuideChapter[]> = {
  it: [
    {
      id: 'ch1_overview',
      icon: 'restaurant',
      title: '1. Panoramica & Architettura Ecosistema',
      subtitle: 'Totem cliente, monitor comande KDS, stampanti termiche e controllo remoto',
      badge: 'ARCHITETTURA',
      paragraphs: [
        'Totem QuickBite è una piattaforma completa per la ristorazione self-service progettata con approccio rigorosamente Local-First.',
        'Tutti i dati, il catalogo menu e le operazioni quotidiane risiedono e comunicano nella rete locale (LAN/Wi-Fi) del locale, garantendo la totale continuità operativa anche in caso di assenza o caduta della connessione Internet esterna.',
      ],
      bulletPoints: [
        { title: '📱 Totem Touchscreen Cliente', desc: 'Interfaccia fluida per ordinazioni autonome self-service o rilascio ticket numerato per ordinare alla cassa.' },
        { title: '🍳 Monitor Comande Cucina KDS', desc: 'Tabellone comande digitale in tempo reale con avanzamento di stato (Da preparare, In preparazione, Pronto, Completato).' },
        { title: '🖨️ Stampanti Termiche ESC/POS', desc: 'Stampa automatica scontrini di cortesia per il cliente e comande suddivise per il banco di preparazione (Bluetooth e Rete LAN).' },
        { title: '🌐 Pannello Remoto LAN & Web', desc: 'Gestione menu, prezzi, esauriti, foto e impostazioni da qualsiasi smartphone, tablet o PC connesso alla stessa rete Wi-Fi.' },
      ],
      tip: 'Collega il totem, il tablet cucina, le stampanti di rete e i dispositivi di cassa allo stesso Wi-Fi del locale per una sincronizzazione istantanea a latenza zero.',
    },
    {
      id: 'ch2_customer_flow',
      icon: 'people',
      title: '2. Percorso Cliente & Selezione Lingue',
      subtitle: 'Dalla schermata di benvenuto alla conferma e ritiro dell’ordine',
      badge: 'CLIENTE',
      paragraphs: [
        'L’interfaccia utente è studiata per abbattere le code ed eliminare gli errori di comanda. Alla prima installazione il sistema è pronto con supporto a 5 lingue internazionali (Italiano, English, Español, Français, Deutsch).',
        'La selezione della lingua effettuata dal cliente in home page vale unicamente per la singola sessione di ordinazione e non altera la lingua amministrativa del locale.',
      ],
      bulletPoints: [
        { title: '1. Scelta Modalità & Lingua', desc: 'Il cliente seleziona la lingua e sceglie tra “Ordina al Totem” (percorso touch interattivo) o “Prendi solo il numero” (ticket per cassa).' },
        { title: '2. Esplorazione Categorie & Piatti', desc: 'Navigazione intuitiva per categorie con foto ad alta risoluzione, prezzi, descrizioni dettagliate ed evidenziazione immediata degli allergeni.' },
        { title: '3. Personalizzazione Piatti', desc: 'Rimozione ingredienti (es. “Senza Cipolla”), aggiunta extra a pagamento (es. “Extra Formaggio”) e scelte obbligatorie/combo (salse, contorni, cottura).' },
        { title: '4. Tipo di Consumazione & Pagamento', desc: 'Selezione tra “Consumo sul posto” o “Asporto” e scelta della modalità di pagamento (alla cassa o integrata).' },
        { title: '5. Emissione Scontrino & Ritiro', desc: 'Generazione istantanea del numero d’ordine progressivo con scontrino di cortesia e invio automatico della comanda in cucina.' },
      ],
      tip: 'Il carrello si azzera automaticamente dopo il tempo di inattività impostato (default 60s) per proteggere la privacy del cliente successivo.',
    },
    {
      id: 'ch3_menu_management',
      icon: 'fast-food',
      title: '3. Gestione Menu, Ingredienti & ⭐ Promo Salvaschermo',
      subtitle: 'Catalogo prodotti, librerie riutilizzabili, varianti e vetrina promozionale',
      badge: 'CATALOGO',
      paragraphs: [
        'Dalla sezione Admin o dal Pannello Remoto Web puoi aggiornare in tempo reale l’intero catalogo pietanze, organizzare le categorie e configurare la promozione visiva.',
        'La scheda Ingredienti permette di creare librerie globali riutilizzabili (salse, modificatori, extra a pagamento) da associare rapidamente a più prodotti senza duplicazioni.',
      ],
      bulletPoints: [
        { title: 'Categorie & Ordinamento', desc: 'Crea e modifica categorie con foto e descrizione; usa le frecce su/giù per stabilire l’ordine esatto di visualizzazione al cliente.' },
        { title: 'Prodotti & Modificatori', desc: 'Definisci prezzi, immagini, allergeni, ingredienti base rimovibili ed elenchi di varianti/combo con vincoli di selezione minima e massima.' },
        { title: '⭐ Pulsante Promo Salvaschermo', desc: 'Posizionato accanto a “Duplica” e “Modifica”, il tasto ⭐ Promo consente di contrassegnare con un tocco i piatti di punta che gireranno nel carosello promozionale quando il totem è in standby.' },
        { title: 'Interruttore Rapido Esaurito', desc: 'Disattiva temporaneamente un prodotto o ingrediente esaurito con un tocco: non sarà ordinabile sul totem fino alla riattivazione.' },
      ],
      tip: 'Modifica prima le librerie nella scheda Ingredienti e poi collegale ai prodotti: manterrai le scelte perfettamente coerenti in tutto il menu.',
    },
    {
      id: 'ch4_kds_kitchen',
      icon: 'flame',
      title: '4. Monitor Comande Cucina (KDS)',
      subtitle: 'Flusso operativo dei cuochi, stati di avanzamento e reset di servizio',
      badge: 'CUCINA KDS',
      paragraphs: [
        'Il modulo KDS (Kitchen Display System) sostituisce i biglietti cartacei con un tabellone digitale interattivo ad alta leggibilità, evidenziando le personalizzazioni e le note speciali dei clienti.',
      ],
      bulletPoints: [
        { title: '🟡 Da Preparare (Giallo)', desc: 'Ricezione istantanea della nuova comanda dal totem con orario esatto, tipo consumazione (Tavolo/Asporto) e modifiche ingredienti evidenziate.' },
        { title: '🔵 In Preparazione (Blu)', desc: 'Il personale di cucina prende in carico la lavorazione toccando “Inizia”, avviando il conteggio dei tempi.' },
        { title: '🟢 Pronto (Verde)', desc: 'La comanda è ultimata e pronta per essere ritirata dal cliente o servita al banco.' },
        { title: '⚪ Azzeramento & Fine Servizio', desc: 'Il comando “Azzera numerazione e comande” riporta il contatore ordini a #1 ed elimina le comande concluse: da eseguire a fine turno.' },
      ],
      tip: 'Se la cucina non dispone di un tablet dedicato, è possibile disattivare la scheda KDS dalle Impostazioni: le stampe e le altre funzioni rimarranno pienamente attive.',
    },
    {
      id: 'ch5_printers',
      icon: 'print',
      title: '5. Stampanti Termiche ESC/POS, Backup & Ripristino',
      subtitle: 'Configurazione Bluetooth, Rete LAN, larghezza carta e salvataggio ZIP',
      badge: 'HARDWARE & BACKUP',
      paragraphs: [
        'Il sistema si interfaccia con stampanti termiche standard ESC/POS (58mm e 80mm), sia via Bluetooth Classic/BLE che tramite connessione di rete LAN (porta TCP standard 9100).',
        'Tutti i dati, le impostazioni, le immagini e il catalogo possono essere esportati in un archivio compresso ZIP per migrazioni rapide o backup di sicurezza.',
      ],
      bulletPoints: [
        { title: 'Separazione Stampante Cassa & Cucina', desc: 'Assegna una stampante per gli scontrini di cortesia del cliente e una stampante distinta per le comande operative del banco cucina.' },
        { title: 'Formato Carta & Stampa Automatica', desc: 'Seleziona larghezza 58mm o 80mm ed abilita la stampa automatica comande non appena l’ordine viene confermato.' },
        { title: 'Esporta Backup ZIP', desc: 'Genera un archivio autonomo con foto, prezzi e configurazioni. Salvalo su chiavetta USB o cloud del gestore.' },
        { title: 'Importa Backup ZIP', desc: 'Ripristina l’intero stato operativo su un nuovo tablet in pochi secondi semplicemente selezionando il file ZIP salvato.' },
      ],
      tip: 'Esegui sempre una stampa di prova dalle Impostazioni prima dell’inizio del servizio per verificare livello carta e stabilità della connessione.',
    },
    {
      id: 'ch6_kiosk_lockdown',
      icon: 'shield-checkmark',
      title: '6. Modalità Totem Protetta, Kiosk & Sicurezza',
      subtitle: 'Blocco schermo intero, LockTask, gesture segreta e credenziali di accesso',
      badge: 'SICUREZZA',
      paragraphs: [
        'Per prevenire manomissioni da parte dei clienti quando il tablet è incassato o esposto al pubblico, Totem QuickBite integra strumenti avanzati di lockdown hardware e software.',
      ],
      bulletPoints: [
        { title: 'Modalità Totem Protetta (Kiosk + Fullscreen)', desc: 'Interruttore unico che attiva la modalità immersiva a schermo intero e nasconde la barra di stato e di navigazione Android.' },
        { title: 'Gesto Segreto di Sblocco (7 Tocchi)', desc: 'Tocca 7 volte rapidamente l’angolo in alto a destra della schermata principale per aprire il tastierino PIN operatore.' },
        { title: 'Credenziali Amministrative Protette', desc: 'Personalizza Username, Password e PIN di sblocco nelle Impostazioni; le credenziali sono cifrate e non vengono mai esposte nei backup.' },
        { title: 'Salvaschermo & Risparmio Energetico', desc: 'Configura il timeout di inattività per avviare il carosello promozionale (con i prodotti contrassegnati da ⭐ Promo) o il dimming notturno dello schermo.' },
      ],
      tip: 'Su tablet Android dedicati, imposta l’applicazione come “Home App / Launcher Predefinito” per abilitare l’auto-avvio all’accensione.',
    },
    {
      id: 'ch7_remote_web',
      icon: 'globe',
      title: '7. Pannello Remoto su Rete Locale (LAN / Web)',
      subtitle: 'Gestione in tempo reale da smartphone, tablet o PC senza toccare il totem',
      badge: 'CONTROLLO REMOTO',
      paragraphs: [
        'Il totem include un server web locale incorporato che consente al gestore di amministrare il locale in mobilità senza interrompere i clienti che stanno ordinando.',
      ],
      bulletPoints: [
        { title: 'Accesso Istantaneo con QR Code', desc: 'Inquadra il QR Code presente nelle Impostazioni del totem con la fotocamera del tuo smartphone per aprire il pannello di controllo.' },
        { title: 'Sincronizzazione Bidirezionale Live', desc: 'Ogni modifica a prezzi, disponibilità o foto effettuata dallo smartphone si riflette immediatamente sullo schermo del totem.' },
        { title: 'Sicurezza Rete Locale', desc: 'L’accesso è protetto da token di sessione e richiede il PIN amministratore; le comunicazioni avvengono esclusivamente sulla Wi-Fi privata del locale.' },
        { title: 'Zero Dipendenza dal Cloud', desc: 'Il pannello remoto funziona interamente tramite il micro-server locale integrato, anche senza connessione a Internet esterna.' },
      ],
      tip: 'Aggiungi l’indirizzo IP del pannello remoto ai preferiti o alla schermata home dello smartphone del responsabile per un accesso con un solo tocco.',
    },
    {
      id: 'ch8_licensing',
      icon: 'ribbon',
      title: '8. Licenza, Aggiornamenti Google Play (AAB / APK) & Manutenzione',
      subtitle: 'Gestione abbonamento, verifiche server e distribuzione build di produzione',
      badge: 'LICENZA & AGGIORNAMENTI',
      paragraphs: [
        'Totem QuickBite è progettato per la pubblicazione ufficiale su Google Play Store tramite bundle AAB (Android App Bundle) e supporta la generazione di APK universali per installazioni dirette su totem industriali.',
      ],
      bulletPoints: [
        { title: 'Abbonamenti Ufficiali Google Play', desc: 'Gestione trasparente dei piani mensili e annuali con addebito sicuro tramite il circuito Google Play Store del tuo account.' },
        { title: 'Verifica & Ripristino Licenza', desc: 'In caso di cambio tablet o reinstallazione, il pulsante “Verifica & Ripristina Abbonamento Google Play” sincronizza automaticamente l’entitlement attivo.' },
        { title: 'Canali di Aggiornamento Ufficiali', desc: 'Gli aggiornamenti software vengono rilasciati tramite Google Play Store per garantire la massima stabilità e conformità alle policy di sicurezza Android.' },
        { title: 'Doppia Pipeline CI/CD GitHub Actions', desc: 'Il workflow di build produce sia il file AAB firmato per il Play Store sia l’APK Universal per test locali o provisioning manuale.' },
      ],
      tip: 'Conserva sempre una copia del backup ZIP in un luogo sicuro prima di eseguire aggiornamenti importanti del sistema operativo Android.',
    },
    {
      id: 'ch9_compliance_privacy',
      icon: 'shield-checkmark',
      title: '9. Conformità Normativa, GDPR & Privacy',
      subtitle: 'Trattamento dati locale, assenza di tracciamento e distinzione fiscale',
      badge: 'CONFORMITÀ & PRIVACY',
      paragraphs: [
        'Totem QuickBite è sviluppato secondo i principi di Privacy by Design e Minimizzazione dei Dati sanciti dal Regolamento Europeo GDPR (UE 2016/679).',
        'Il funzionamento è 100% locale: nessuna profilazione utente, nessun dato sensibile trasmesso all’esterno.',
      ],
      bulletPoints: [
        { title: '🔒 Zero Dati Personali dei Clienti', desc: 'Il totem non richiede né memorizza nomi, indirizzi e-mail, numeri di telefono o dati di pagamento dei consumatori.' },
        { title: '🛡️ Pulizia Automatica della Sessione', desc: 'Al termine dell’ordine o dopo il timeout di inattività, tutte le selezioni del carrello e le preferenze di lingua temporanee vengono azzerate all’istante.' },
        { title: '🧾 Distinzione Fiscale & Comanda di Servizio', desc: 'I ticket emessi dal totem sono scontrini di cortesia e promemoria di preparazione interna; l’adempimento fiscale definitivo compete al Registratore Telematico di cassa del locale.' },
        { title: '♿ Accessibilità & Standard Touch', desc: 'Pulsanti tattili ad alto contrasto con target di tocco conformi (>48px) e navigazione facilitata per utenti internazionali in 5 lingue.' },
      ],
      tip: 'Tutti i log e il catalogo prodotti risiedono esclusivamente nello spazio di archiviazione protetto del dispositivo locale.',
    },
    {
      id: 'ch10_multi_totem_printers',
      icon: 'layers',
      title: '10. Architettura Multi-Totem, Master/Satellite & Multi-Stampanti Reparti',
      subtitle: 'Configurazione multi-postazione, licenza Google Play centralizzata, stampanti e KDS illimitati',
      badge: 'MULTI-TOTEM & HARDWARE',
      paragraphs: [
        'Totem QuickBite supporta nativamente configurazioni avanzate ad alte prestazioni: sia in modalità Mono Totem (postazione singola autonoma) sia in modalità Multi-Totem (rete Master/Satellite su LAN locale).',
        'Tutti i dispositivi eseguono la medesima applicazione: la licenza Google Play Store viene acquistata e gestita unicamente sul Totem Master (Principale), mentre tutti i Totem Satelliti (Secondari) si collegano in LAN locale ereditando automaticamente catalogo, stato licenza e numerazione ordini a latenza zero.',
      ],
      bulletPoints: [
        { title: '👑 Totem Master (Server LAN)', desc: 'Contiene la licenza Google Play attiva e funge da coordinatore della rete locale per menu, prezzi e numerazione unificata delle comande.' },
        { title: '🛰️ Totem Satelliti Illimitati', desc: 'Postazioni kiosk aggiuntive per abbattere le code nei momenti di punta. I satelliti sincronizzano automaticamente il menu dal Master e inviano le comande sulla rete locale senza costi di licenza aggiuntivi.' },
        { title: '🖨️ Multi-Stampanti Illimitate per Reparto', desc: 'Collega quante stampanti termiche desideri (Cucina Calda, Pizzeria/Forno, Bar/Bevande, Cassa Cortesia). Assegna a ogni stampante le relative categorie di prodotti per un instradamento automatico e mirato.' },
        { title: '📺 KDS Multi-Reparto Speculare', desc: 'I monitor di cucina (KDS) rispecchiano esattamente i reparti delle stampanti: ogni postazione di lavoro (es. Bar o Pizzeria) visualizza sul proprio schermo solo gli articoli di propria competenza.' },
        { title: '🔍 Auto-Discovery & Sincronizzazione LAN', desc: 'I totem satelliti trovano automaticamente il Master nella rete Wi-Fi tramite la funzione “Cerca Master in Rete (LAN)” con collegamento in 1 tocco.' },
      ],
      tip: 'Assegna un prefisso univoco alle comande per ciascun totem (es. T1- per il Master e T2- per il Satellite) per identificare istantaneamente la cassa di provenienza.',
    },
    {
      id: 'ch11_kds_routing',
      icon: 'restaurant',
      title: '11. Routing Multi-Stampante & Categorie KDS',
      subtitle: 'Gestione avanzata delle comande divise per reparto e stampanti Bluetooth.',
      badge: 'AVANZATO',
      paragraphs: [
        'La piattaforma supporta l\'assegnazione diretta di categorie (es. Pizze, Bevande) a specifici schermi KDS e Stampanti Bluetooth.',
        'Vai nella scheda Impostazioni -> Stampa del Totem per rilevare e accoppiare più stampanti Bluetooth.',
        'Per ogni stampante o monitor KDS, puoi selezionare le categorie di cui si occupa. Le comande verranno divise automaticamente e inviate ai reparti corretti.'
      ],
      tip: 'Suggerimento: se non selezioni nessuna categoria, la stampante o il KDS riceverà l\'intero ordine globale.'
    },
  ],

  en: [
    {
      id: 'ch1_overview',
      icon: 'restaurant',
      title: '1. Overview & System Architecture',
      subtitle: 'Customer totem, kitchen KDS display, thermal printers and remote management',
      badge: 'ARCHITECTURE',
      paragraphs: [
        'QuickBite Totem is a comprehensive self-service restaurant platform engineered with a strict Local-First approach.',
        'All data, menu items, and daily operations run locally on the restaurant’s LAN / Wi-Fi network, ensuring total operational uptime even during internet outages.',
      ],
      bulletPoints: [
        { title: '📱 Customer Touchscreen Totem', desc: 'Smooth touch interface for independent customer ordering or issuing numbered queue tickets for counter ordering.' },
        { title: '🍳 Digital Kitchen KDS Display', desc: 'Real-time kitchen order board tracking progress statuses (To Prepare, Preparing, Ready, Completed).' },
        { title: '🖨️ ESC/POS Thermal Printers', desc: 'Automatic printing of customer courtesy receipts and kitchen prep dockets (Bluetooth & LAN Network).' },
        { title: '🌐 LAN & Web Remote Panel', desc: 'Manage catalog, prices, sold-out toggles, photos, and settings from any smartphone or PC on the same Wi-Fi.' },
      ],
      tip: 'Connect the totem, kitchen display, network printers, and management devices to the same local Wi-Fi for zero-latency instant sync.',
    },
    {
      id: 'ch2_customer_flow',
      icon: 'people',
      title: '2. Customer Journey & 5-Language Selection',
      subtitle: 'From welcome screen to order customization and receipt pickup',
      badge: 'CUSTOMER',
      paragraphs: [
        'The UI is designed to eliminate queues and ordering mistakes. The system features built-in support for 5 international languages (Italian, English, Spanish, French, German).',
        'Customer language selection applies strictly to the active ordering session and does not alter the administrative manager language.',
      ],
      bulletPoints: [
        { title: '1. Language & Mode Selection', desc: 'Customers pick their language and choose between “Order at Totem” (interactive touch menu) or “Take a Number Only” (counter ticket).' },
        { title: '2. Menu Browsing', desc: 'Intuitive category navigation with high-res photos, clear pricing, descriptions, and prominent allergen indicators.' },
        { title: '3. Dish Customization', desc: 'Remove base ingredients (“No Onions”), add paid extras (“Extra Cheese”), and configure mandatory combo choices (sauces, sides, cooking preferences).' },
        { title: '4. Dining Preference & Payment', desc: 'Choose between “Dine-In” or “Takeaway” and select the payment method (at checkout counter or on kiosk).' },
        { title: '5. Receipt & Collection', desc: 'Instant order number generation with customer courtesy slip and automatic order dispatch to kitchen.' },
      ],
      tip: 'The shopping cart automatically resets after the configured inactivity timeout (default 60s) to protect customer privacy.',
    },
    {
      id: 'ch3_menu_management',
      icon: 'fast-food',
      title: '3. Menu Management, Ingredients & ⭐ Promo Screensaver',
      subtitle: 'Product catalog, reusable option libraries, variants and visual showcase',
      badge: 'CATALOG',
      paragraphs: [
        'From the Admin tab or the Web Remote Panel, you can update dishes, organize categories, and configure promotional banners in real time.',
        'The Ingredients tab lets you build reusable global option groups (sauces, modifiers, paid extras) that can be linked across multiple dishes without redundant data entry.',
      ],
      bulletPoints: [
        { title: 'Categories & Display Order', desc: 'Create and edit categories with photos and descriptions; use up/down arrows to set the customer sequence.' },
        { title: 'Products & Modifiers', desc: 'Set prices, photos, allergens, removable base ingredients, and option groups with minimum and maximum selection limits.' },
        { title: '⭐ Promo Screensaver Star Button', desc: 'Located beside “Duplicate” and “Edit”, the ⭐ Promo button lets you highlight top items with a single tap to appear on the idle promo carousel.' },
        { title: 'Instant Sold-Out Toggle', desc: 'Temporarily disable an out-of-stock item or ingredient in one click to stop incoming customer orders immediately.' },
      ],
      tip: 'Create modifier collections in the Ingredients tab first, then link them to products for consistent menu choices.',
    },
    {
      id: 'ch4_kds_kitchen',
      icon: 'flame',
      title: '4. Kitchen Display System (KDS)',
      subtitle: 'Cook workflow, live preparation tracking and end-of-day reset',
      badge: 'KITCHEN KDS',
      paragraphs: [
        'The Kitchen Display System replaces paper tickets with a dynamic, high-visibility digital board that highlights customer customizations and special kitchen notes.',
      ],
      bulletPoints: [
        { title: '🟡 To Prepare (Yellow)', desc: 'Instant order reception from totem with exact timestamp, dining type (Dine-in/Takeaway), and highlighted ingredient modifications.' },
        { title: '🔵 Preparing (Blue)', desc: 'Kitchen crew starts order preparation by tapping “Start”, tracking waiting times.' },
        { title: '🟢 Ready (Green)', desc: 'Order is fully prepared and ready for customer collection or counter delivery.' },
        { title: '⚪ Reset & Service End', desc: '“Reset numbering and orders” resets next order number to #1 and clears finished tickets at the end of the shift.' },
      ],
      tip: 'If your kitchen does not use a dedicated tablet, disable Kitchen Orders Display in Settings: printing and other features remain fully operational.',
    },
    {
      id: 'ch5_printers',
      icon: 'print',
      title: '5. ESC/POS Thermal Printers, ZIP Backup & Restore',
      subtitle: 'Bluetooth & LAN network setup, paper width and portable ZIP archives',
      badge: 'HARDWARE & BACKUP',
      paragraphs: [
        'The system supports standard ESC/POS thermal printers (58mm and 80mm), connecting via Bluetooth Classic/BLE or local LAN network (standard port 9100).',
        'All settings, images, and menu configurations can be exported into a single ZIP archive for fast tablet migration or safe backups.',
      ],
      bulletPoints: [
        { title: 'Customer & Kitchen Printer Separation', desc: 'Assign one printer for customer courtesy receipts and a separate printer for kitchen preparation dockets.' },
        { title: 'Paper Width & Auto-Printing', desc: 'Select 58mm or 80mm paper width and enable automatic printing upon customer order confirmation.' },
        { title: 'Export ZIP Backup', desc: 'Generate a self-contained archive of your entire catalog, photos, and settings to save on USB drive or cloud storage.' },
        { title: 'Import ZIP Backup', desc: 'Restore your entire restaurant configuration on any replacement tablet in seconds by selecting the saved ZIP file.' },
      ],
      tip: 'Always perform a Test Print from Settings before service hours to verify paper roll level and connection stability.',
    },
    {
      id: 'ch6_kiosk_lockdown',
      icon: 'shield-checkmark',
      title: '6. Protected Totem Mode, Kiosk Lockdown & Security',
      subtitle: 'Fullscreen immersive lock, LockTask, secret 7-tap gesture and admin PIN',
      badge: 'SECURITY',
      paragraphs: [
        'To prevent tampering when the tablet is enclosure-mounted or accessible to the public, QuickBite Totem features robust hardware and software kiosk controls.',
      ],
      bulletPoints: [
        { title: 'Protected Totem Mode (Kiosk + Fullscreen)', desc: 'Single master toggle that engages immersive fullscreen mode and conceals the Android status and navigation bars.' },
        { title: 'Secret Unlock Gesture (7 Taps)', desc: 'Tap 7 times quickly in the top-right corner of the welcome screen to open the operator PIN keypad.' },
        { title: 'Protected Admin Credentials', desc: 'Customize Username, Password, and security PIN in Settings; credentials are encrypted and never exposed in backup files.' },
        { title: 'Screensaver & Energy Saving', desc: 'Configure inactivity timers to launch the promotional carousel (featuring items tagged with ⭐ Promo) or enable scheduled nighttime screen dimming.' },
      ],
      tip: 'On dedicated Android hardware, set this app as the “Default Home / Launcher App” to enable automatic launch on power-on.',
    },
    {
      id: 'ch7_remote_web',
      icon: 'globe',
      title: '7. Local Network Remote Admin Panel (LAN / Web)',
      subtitle: 'Real-time wireless management from smartphone, tablet, or PC',
      badge: 'REMOTE CONTROL',
      paragraphs: [
        'The totem includes an embedded local web server allowing the manager to update the restaurant on the fly without interrupting ordering customers.',
      ],
      bulletPoints: [
        { title: 'Instant QR Code Access', desc: 'Scan the QR code in Totem Settings with your mobile camera to launch the remote web management panel.' },
        { title: 'Live Bidirectional Sync', desc: 'Any change to prices, photos, or stock availability made from your phone updates the totem screen immediately.' },
        { title: 'Local Network Security', desc: 'Access is guarded by session tokens and requires your admin PIN; traffic remains strictly within the restaurant’s private Wi-Fi.' },
        { title: 'Zero Cloud Dependency', desc: 'The remote web panel is served directly by the totem’s internal engine, operating seamlessly even without internet access.' },
      ],
      tip: 'Bookmark the remote web URL on your smartphone for convenient one-tap access.',
    },
    {
      id: 'ch8_licensing',
      icon: 'ribbon',
      title: '8. Licensing, Google Play Updates (AAB / APK) & Maintenance',
      subtitle: 'Subscription management, store verification and production build distribution',
      badge: 'LICENSING & UPDATES',
      paragraphs: [
        'QuickBite Totem is engineered for official release on the Google Play Store via signed AAB (Android App Bundle) packages and supports Universal APK builds for standalone kiosk hardware.',
      ],
      bulletPoints: [
        { title: 'Official Google Play Subscriptions', desc: 'Transparent monthly and annual plans billed securely through your Google Play Store account.' },
        { title: 'Verify & Restore Subscription', desc: 'When switching tablets or reinstalling, the “Verify & Restore Google Play Subscription” button re-validates your active entitlement.' },
        { title: 'Official Update Channels', desc: 'Software updates are distributed through Google Play Store for maximum stability and compliance with Android security policies.' },
        { title: 'Dual CI/CD Pipeline (GitHub Actions)', desc: 'The automated build system produces both the signed AAB bundle for Play Store review and the Universal APK for direct hardware installation.' },
      ],
      tip: 'Always export a ZIP backup to safe storage before performing major Android OS updates.',
    },
    {
      id: 'ch9_compliance_privacy',
      icon: 'shield-checkmark',
      title: '9. Regulatory Compliance, GDPR & Privacy',
      subtitle: 'Local-only data storage, zero customer tracking and fiscal compliance',
      badge: 'COMPLIANCE & PRIVACY',
      paragraphs: [
        'QuickBite Totem is developed in compliance with GDPR Privacy by Design principles (EU 2016/679).',
        'Operations are 100% local: no customer profiling and zero private data transmitted to external servers.',
      ],
      bulletPoints: [
        { title: '🔒 Zero Customer Personal Data Retained', desc: 'The kiosk does not record names, emails, phone numbers, or credit card details of customers.' },
        { title: '🛡️ Automated Session Purge', desc: 'Upon order completion or inactivity timeout, all cart selections and temporary language preferences are wiped immediately.' },
        { title: '🧾 Fiscal & Kitchen Docket Separation', desc: 'Kiosk receipts act as customer courtesy dockets and internal kitchen prep tickets; definitive fiscal registration is handled by certified cash registers.' },
        { title: '♿ Touch Accessibility Standards', desc: 'High-contrast touch targets (>48px) and effortless 5-language international support.' },
      ],
      tip: 'All database records remain stored securely inside the local device protected sandbox.',
    },
    {
      id: 'ch10_multi_totem_printers',
      icon: 'layers',
      title: '10. Multi-Kiosk Architecture, Master/Satellite & Department Multi-Printers',
      subtitle: 'Multi-station network setup, centralized Google Play licensing, unlimited printers & KDS',
      badge: 'MULTI-KIOSK & HARDWARE',
      paragraphs: [
        'QuickBite Totem natively supports both Single Kiosk (standalone) and Multi-Kiosk (Master/Satellite LAN network) enterprise environments.',
        'All stations run the exact same app: your Google Play Store subscription is managed strictly on the Master Kiosk, while unlimited Satellite Kiosks connect over the local LAN, inheriting menu items, real-time license status, and order numbering with zero cloud latency.',
      ],
      bulletPoints: [
        { title: '👑 Master Kiosk (LAN Coordinator)', desc: 'Holds the active Google Play license and coordinates the local restaurant network, menu prices, categories, and synchronized order numbers.' },
        { title: '🛰️ Unlimited Satellite Kiosks', desc: 'Secondary touchscreen stations that eliminate queue bottlenecks. Satellites pull live catalog data from the Master and broadcast orders locally.' },
        { title: '🖨️ Unlimited Department Printers', desc: 'Deploy dedicated thermal printers for Hot Kitchen, Pizza Oven, Bar/Drinks, and Customer Courtesy. Assign specific product categories to each printer for precise routing.' },
        { title: '📺 Mirrored Multi-Department KDS', desc: 'Kitchen displays automatically reflect printer departments: kitchen staff, pizza chefs, and bartenders only see their respective order items.' },
        { title: '🔍 LAN Auto-Discovery & 1-Click Sync', desc: 'Satellite kiosks discover the local Master node instantly with the built-in “Scan LAN for Master” tool.' },
      ],
      tip: 'Configure distinctive order prefixes for each totem (e.g., T1- for Master, T2- for Satellite) to easily trace order origin at checkout.',
    },
    {
      id: 'ch11_kds_routing',
      icon: 'restaurant',
      title: '11. Multi-Printer Routing & KDS Categories',
      subtitle: 'Advanced order management divided by department and Bluetooth printers.',
      badge: 'ADVANCED',
      paragraphs: [
        'The platform supports assigning specific categories (e.g., Pizzas, Drinks) to dedicated KDS screens and Bluetooth Printers.',
        'Go to Settings -> Printing on the Totem to detect and pair multiple Bluetooth printers.',
        'For each printer or KDS monitor, select the categories it handles. Orders will be automatically split and sent to the correct departments.'
      ],
      tip: 'Pro Tip: If you do not select any category, the printer or KDS will receive the entire global order.'
    },
  ],

  es: [
    {
      id: 'ch1_overview',
      icon: 'restaurant',
      title: '1. Visión General & Arquitectura del Ecosistema',
      subtitle: 'Tótem cliente, pantalla de cocina KDS, impresoras térmicas y gestión remota',
      badge: 'ARQUITECTURA',
      paragraphs: [
        'QuickBite Totem es una plataforma integral para hostelería y restauración autoservicio diseñada con un enfoque estrictamente Local-First.',
        'Todos los datos, el catálogo y las operaciones diarias funcionan en la red local (LAN/Wi-Fi) del establecimiento, garantizando el servicio ininterrumpido incluso sin conexión a Internet.',
      ],
      bulletPoints: [
        { title: '📱 Tótem Táctil Cliente', desc: 'Interfaz táctil intuitiva para pedidos autónomos o emisión de números de turno para pedir en caja.' },
        { title: '🍳 Pantalla de Cocina KDS', desc: 'Panel de comandas digital en tiempo real con estados (Para preparar, En preparación, Listo, Completado).' },
        { title: '🖨️ Impresoras Térmicas ESC/POS', desc: 'Impresión automática de recibos para clientes y comandas de preparación (Bluetooth y Red LAN).' },
        { title: '🌐 Panel Remoto LAN & Web', desc: 'Gestión de platos, precios, fotos y opciones desde cualquier móvil o PC conectado al mismo Wi-Fi.' },
      ],
      tip: 'Conecte el tótem, la pantalla de cocina, las impresoras de red y los dispositivos de gestión al mismo Wi-Fi del local para sincronización instantánea.',
    },
    {
      id: 'ch2_customer_flow',
      icon: 'people',
      title: '2. Recorrido del Cliente & Selección de Idioma',
      subtitle: 'Desde la pantalla de bienvenida hasta la personalización y recogida del pedido',
      badge: 'CLIENTE',
      paragraphs: [
        'La interfaz de usuario elimina colas y errores en los pedidos. Incluye soporte para 5 idiomas (Italiano, English, Español, Français, Deutsch).',
        'El idioma elegido por el cliente en la pantalla inicial se aplica solo a su pedido actual y no altera el idioma administrativo del gestor.',
      ],
      bulletPoints: [
        { title: '1. Selección de Idioma & Modo', desc: 'El cliente elige idioma y selecciona “Pedir en el Tótem” o “Tomar solo un número” para pagar en caja.' },
        { title: '2. Exploración del Menú', desc: 'Categorías claras, fotos en alta resolución, descripciones detalladas, precios e indicación de alérgenos.' },
        { title: '3. Personalización de Platos', desc: 'Eliminación de ingredientes base (“Sin Cebolla”), extras de pago (“Extra Queso”) y opciones obligatorias/combos.' },
        { title: '4. Tipo de Consumo & Pago', desc: 'Elección entre “Consumir en el local” o “Para llevar” y selección del método de pago.' },
        { title: '5. Emisión de Recibo & Recogida', desc: 'Generación del número de pedido progresivo con ticket de cortesía y envío instantáneo a cocina.' },
      ],
      tip: 'El carrito se vacía automáticamente tras el tiempo de inactividad configurado (por defecto 60s) para proteger la privacidad.',
    },
    {
      id: 'ch3_menu_management',
      icon: 'fast-food',
      title: '3. Gestión del Menú, Ingredientes & ⭐ Promo Salvapantallas',
      subtitle: 'Catálogo, librerías reutilizables, variantes y escaparate promocional',
      badge: 'CATÁLOGO',
      paragraphs: [
        'Desde el área Admin o el Panel Remoto Web puede actualizar platos, organizar categorías y configurar promociones visuales en tiempo real.',
        'La pestaña Ingredientes permite crear grupos de opciones globales reutilizables (salsas, extras de pago) vinculables a múltiples platos.',
      ],
      bulletPoints: [
        { title: 'Categorías y Posición', desc: 'Cree y ordene categorías con fotos y descripciones mediante las flechas arriba/abajo.' },
        { title: 'Productos y Modificadores', desc: 'Configure precios, fotos, alérgenos, ingredientes base eliminables y reglas de selección mínima/máxima.' },
        { title: '⭐ Botón Promo Salvapantallas', desc: 'Junto a “Duplicar” y “Editar”, el botón ⭐ Promo marca los platos destacados que girarán en el carrusel en reposo.' },
        { title: 'Interruptor Rápido de Agotado', desc: 'Desactive temporalmente un producto o ingrediente agotado con un toque para evitar nuevos pedidos.' },
      ],
      tip: 'Cree primero las librerías en la pestaña Ingredientes y vincúlelas a los productos para mantener opciones coherentes en el menú.',
    },
    {
      id: 'ch4_kds_kitchen',
      icon: 'flame',
      title: '4. Pantalla de Comandas de Cocina (KDS)',
      subtitle: 'Flujo de preparación, tiempos de espera y reinicio de fin de servicio',
      badge: 'COCINA KDS',
      paragraphs: [
        'El sistema KDS sustituye los tickets de papel por un panel digital interactivo que resalta claramente las modificaciones y notas de los clientes.',
      ],
      bulletPoints: [
        { title: '🟡 Para Preparar (Amarillo)', desc: 'Recepción instantánea de la comanda con hora exacta, tipo de consumo y cambios de ingredientes destacados.' },
        { title: '🔵 En Preparación (Azul)', desc: 'El equipo de cocina pulsa “Iniciar” para registrar el comienzo del trabajo y controlar tiempos.' },
        { title: '🟢 Listo (Verde)', desc: 'La comanda está finalizada y lista para entrega o recogida en mostrador.' },
        { title: '⚪ Reinicio & Fin de Turno', desc: '“Restablecer numeración y pedidos” vuelve el contador a #1 y limpia las comandas finalizadas al cierre.' },
      ],
      tip: 'Si la cocina no dispone de tablet propia, desactive Pantalla de Cocina en Ajustes: la impresión continuará funcionando.',
    },
    {
      id: 'ch5_printers',
      icon: 'print',
      title: '5. Impresoras Térmicas ESC/POS, Copia de Seguridad & Restauración',
      subtitle: 'Configuración Bluetooth, Red LAN, formato de papel y archivos ZIP portátiles',
      badge: 'HARDWARE & COPIAS',
      paragraphs: [
        'Compatible con impresoras térmicas ESC/POS de 58mm y 80mm (Bluetooth Classic/BLE o Red LAN puerto 9100).',
        'Toda la configuración, fotos y datos se pueden exportar a un archivo ZIP para migraciones rápidas o copias de seguridad.',
      ],
      bulletPoints: [
        { title: 'Separación Impresora Caja & Cocina', desc: 'Asigne una impresora para tickets de cliente y otra independiente para comandas de cocina.' },
        { title: 'Ancho de Papel & Impresión Automática', desc: 'Seleccione 58mm u 80mm y active la impresión automática al confirmar el pedido.' },
        { title: 'Exportar Copia ZIP', desc: 'Genere un archivo completo con su menú, fotos y ajustes para guardarlo en USB o en la nube.' },
        { title: 'Importar Copia ZIP', desc: 'Restaure su terminal en segundos en una nueva tablet simplemente seleccionando el archivo ZIP.' },
      ],
      tip: 'Realice siempre una impresión de prueba desde Ajustes antes de iniciar el servicio.',
    },
    {
      id: 'ch6_kiosk_lockdown',
      icon: 'shield-checkmark',
      title: '6. Modo Tótem Protegido, Bloqueo Kiosco & Seguridad',
      subtitle: 'Bloqueo a pantalla completa, LockTask, gesto de 7 toques y PIN de seguridad',
      badge: 'SEGURIDAD',
      paragraphs: [
        'Para evitar manipulaciones no autorizadas por parte del público, QuickBite Totem incorpora controles avanzados de modo kiosco.',
      ],
      bulletPoints: [
        { title: 'Modo Tótem Protegido (Kiosco + Pantalla Completa)', desc: 'Interruptor maestro que oculta las barras de estado y navegación de Android.' },
        { title: 'Gesto Secreto de Desbloqueo (7 Toques)', desc: 'Toque 7 veces rápidamente la esquina superior derecha para abrir el teclado PIN de administrador.' },
        { title: 'Credenciales de Administrador Protegidas', desc: 'Configure Usuario, Contraseña y PIN en Ajustes; las credenciales se almacenan cifradas.' },
        { title: 'Salvapantallas & Ahorro de Energía', desc: 'Configure el tiempo de reposo para activar el carrusel de productos ⭐ Promo o el atenuado nocturno.' },
      ],
      tip: 'En tablets Android dedicadas, establezca la aplicación como “App de Inicio Predeterminada” para autoarranque.',
    },
    {
      id: 'ch7_remote_web',
      icon: 'globe',
      title: '7. Panel Remoto en Red Local (LAN / Web)',
      subtitle: 'Gestión inalámbrica en tiempo real desde móvil, tablet o PC',
      badge: 'CONTROL REMOTO',
      paragraphs: [
        'El tótem incluye un servidor web integrado que permite al responsable administrar el restaurante sin interrumpir a los clientes.',
      ],
      bulletPoints: [
        { title: 'Acceso Inmediato con Código QR', desc: 'Escanee el código QR en Ajustes con la cámara del móvil para abrir el panel de control web.' },
        { title: 'Sincronización Bidireccional en Vivo', desc: 'Cualquier cambio de precios o platos desde el móvil se actualiza al instante en el tótem.' },
        { title: 'Seguridad en Red Local', desc: 'Protegido por token de sesión y PIN; las comunicaciones no salen del Wi-Fi privado del local.' },
        { title: 'Cero Dependencia de la Nube', desc: 'Funciona enteramente en el servidor local del tótem, incluso sin conexión a Internet externa.' },
      ],
      tip: 'Guarde la dirección web en los marcadores de su teléfono para acceder con un solo toque.',
    },
    {
      id: 'ch8_licensing',
      icon: 'ribbon',
      title: '8. Licencia, Actualizaciones Google Play (AAB / APK) & Mantenimiento',
      subtitle: 'Gestión de suscripciones, validación y distribución de paquetes de producción',
      badge: 'LICENCIA & ACTUALIZACIONES',
      paragraphs: [
        'QuickBite Totem está diseñado para su publicación oficial en Google Play Store mediante paquetes AAB y admite APK universales para instalación directa en hardware de kiosco.',
      ],
      bulletPoints: [
        { title: 'Suscripciones Oficiales Google Play', desc: 'Planes mensuales y anuales facturados de forma segura a través de su cuenta de Google Play.' },
        { title: 'Verificar & Restaurar Suscripción', desc: 'El botón “Verificar y Restaurar Suscripción” reactiva su licencia en cualquier nuevo dispositivo.' },
        { title: 'Canales de Actualización Oficiales', desc: 'Las actualizaciones se distribuyen a través de Google Play Store para máxima estabilidad.' },
        { title: 'Doble Pipeline CI/CD (GitHub Actions)', desc: 'Generación automatizada de bundle AAB firmado y APK Universal para pruebas y despliegue.' },
      ],
      tip: 'Guarde siempre una copia de seguridad ZIP antes de realizar actualizaciones importantes del sistema operativo Android.',
    },
    {
      id: 'ch9_compliance_privacy',
      icon: 'shield-checkmark',
      title: '9. Cumplimiento Normativo, RGPD & Privacidad',
      subtitle: 'Almacenamiento 100% local, cero rastreo y separación fiscal',
      badge: 'CUMPLIMIENTO & PRIVACIDAD',
      paragraphs: [
        'Desarrollado conforme a los principios de Privacidad desde el Diseño del RGPD (UE 2016/679).',
        'Operación completamente local: sin recopilación de datos privados ni envíos a servidores de terceros.',
      ],
      bulletPoints: [
        { title: '🔒 Cero Datos Personales de Clientes', desc: 'No se solicitan ni almacenan nombres, correos, teléfonos ni datos bancarios de los comensales.' },
        { title: '🛡️ Borrado Automático de Sesión', desc: 'Al finalizar el pedido o por inactividad, el carrito y el idioma temporal se eliminan de inmediato.' },
        { title: '🧾 Comprobantes de Cortesía & Factura Fiscal', desc: 'Los tickets del tótem son comandas de servicio internas; la factura fiscal final se emite en la caja registradora habilitada.' },
        { title: '♿ Accesibilidad Táctil', desc: 'Botones táctiles de alto contraste (>48px) y soporte multilingüe en 5 idiomas.' },
      ],
      tip: 'Los datos del menú permanecen almacenados de forma segura en la memoria interna del dispositivo.',
    },
    {
      id: 'ch10_multi_totem_printers',
      icon: 'layers',
      title: '10. Arquitectura Multi-Tótem, Maestro/Satélite & Multi-Impresoras por Departamento',
      subtitle: 'Configuración multipuesto, licencia centralizada de Google Play, impresoras y KDS ilimitados',
      badge: 'MULTI-TÓTEM & HARDWARE',
      paragraphs: [
        'QuickBite Totem admite tanto el modo Tótem Único como el modo Multi-Tótem de alto rendimiento (red local Maestro/Satélite).',
        'Todos los dispositivos ejecutan la misma aplicación: la suscripción de Google Play se gestiona únicamente en el Tótem Maestro, mientras que los Tótems Satélites se conectan por LAN local heredando catálogo, licencia y numeración sin costes añadidos.',
      ],
      bulletPoints: [
        { title: '👑 Tótem Maestro (Servidor LAN)', desc: 'Gestiona la licencia de Google Play y coordina el catálogo, precios y numeración unificada en toda la red local.' },
        { title: '🛰️ Tótems Satélites Ilimitados', desc: 'Puestos adicionales para agilizar colas. Sincronizan el menú en tiempo real desde el Maestro y transmiten pedidos localmente.' },
        { title: '🖨️ Multi-Impresoras Ilimitadas por Departamento', desc: 'Conecte impresoras térmicas para Cocina, Pizzería/Horno, Bar y Recibos. Asigne categorías de productos a cada impresora para enrutamiento automático.' },
        { title: '📺 Pantallas KDS por Departamento', desc: 'Las pantallas de cocina reflejan los departamentos de impresión: cada sección visualiza exclusivamente sus platos correspondientes.' },
        { title: '🔍 Detección Automática en Red LAN', desc: 'Los satélites localizan el Maestro en el Wi-Fi local mediante la función “Buscar Maestro en Red LAN”.' },
      ],
      tip: 'Defina un prefijo para cada tótem (ej. T1- y T2-) para identificar al instante el origen del pedido.',
    },
    {
      id: 'ch11_kds_routing',
      icon: 'restaurant',
      title: '11. Enrutamiento Multi-Impresora y Categorías KDS',
      subtitle: 'Gestión avanzada de pedidos divididos por departamento e impresoras Bluetooth.',
      badge: 'AVANZADO',
      paragraphs: [
        'La plataforma admite la asignación directa de categorías (ej. Pizzas, Bebidas) a pantallas KDS específicas e impresoras Bluetooth.',
        'Ve a la pestaña Configuración -> Impresión del Tótem para detectar y vincular múltiples impresoras Bluetooth.',
        'Para cada impresora o monitor KDS, selecciona las categorías de las que se encarga. Los pedidos se dividirán automáticamente y se enviarán a los departamentos correctos.'
      ],
      tip: 'Consejo: Si no seleccionas ninguna categoría, la impresora o KDS recibirá todo el pedido global.'
    },
  ],

  fr: [
    {
      id: 'ch1_overview',
      icon: 'restaurant',
      title: '1. Présentation & Architecture de l’Écosystème',
      subtitle: 'Borne client, écran cuisine KDS, imprimantes thermiques et gestion à distance',
      badge: 'ARCHITECTURE',
      paragraphs: [
        'Totem QuickBite est une solution complète de commande autonome pour la restauration conçue selon une approche strictement Local-First.',
        'Toutes les données, la carte et les opérations quotidiennes s’exécutent sur le réseau local (LAN/Wi-Fi) de l’établissement, garantissant une continuité totale même en cas de coupure Internet.',
      ],
      bulletPoints: [
        { title: '📱 Borne Tactile Client', desc: 'Interface fluide pour la commande autonome ou la délivrance de tickets numérotés pour la caisse.' },
        { title: '🍳 Écran Cuisine KDS Numérique', desc: 'Tableau des commandes en direct avec statuts (À préparer, En préparation, Prêt, Terminé).' },
        { title: '🖨️ Imprimantes Thermiques ESC/POS', desc: 'Impression automatique des tickets de courtoisie clients et des bons de préparation cuisine (Bluetooth & Réseau LAN).' },
        { title: '🌐 Panneau Distant LAN & Web', desc: 'Gestion de la carte, des prix, des ruptures et des photos depuis tout smartphone ou PC connecté au même Wi-Fi.' },
      ],
      tip: 'Connectez la borne, l’écran cuisine, les imprimantes réseau et les appareils de gestion au même Wi-Fi pour une synchronisation instantanée.',
    },
    {
      id: 'ch2_customer_flow',
      icon: 'people',
      title: '2. Parcours Client & Sélection des Langues',
      subtitle: 'De l’écran d’accueil à la personnalisation et au retrait de la commande',
      badge: 'CLIENT',
      paragraphs: [
        'L’interface utilisateur élimine les files d’attente et les erreurs de commande. Elle intègre 5 langues internationales (Italiano, English, Español, Français, Deutsch).',
        'Le choix de la langue par le client sur l’accueil s’applique uniquement à sa session et ne modifie pas la langue d’administration de l’établissement.',
      ],
      bulletPoints: [
        { title: '1. Choix du Mode & de la Langue', desc: 'Le client choisit sa langue et sélectionne « Commander à la borne » ou « Prendre seulement un numéro ».' },
        { title: '2. Découverte du Menu', desc: 'Navigation intuitive par catégories avec photos haute définition, prix, descriptions détaillées et allergènes visibles.' },
        { title: '3. Personnalisation des Plats', desc: 'Retrait d’ingrédients (« Sans Oignon »), suppléments payants (« Extra Fromage ») et choix obligatoires/menus.' },
        { title: '4. Type de Consommation & Paiement', desc: 'Sélection entre « Sur place » ou « À emporter » et choix du mode de règlement.' },
        { title: '5. Reçu & Retrait', desc: 'Génération instantanée du numéro de commande progressif avec reçu client et transmission automatique en cuisine.' },
      ],
      tip: 'Le panier se réinitialise automatiquement après le délai d’inactivité configuré (par défaut 60s) pour préserver la confidentialité.',
    },
    {
      id: 'ch3_menu_management',
      icon: 'fast-food',
      title: '3. Gestion du Menu, Ingrédients & ⭐ Promo Économiseur',
      subtitle: 'Catalogue, bibliothèques réutilisables, variantes et vitrine promotionnelle',
      badge: 'CATALOGUE',
      paragraphs: [
        'Depuis la zone Admin ou le Panneau Distant Web, vous pouvez mettre à jour la carte et configurer la vitrine promotionnelle en temps réel.',
        'L’onglet Ingrédients permet de créer des collections d’options globales réutilisables (sauces, suppléments) à lier à plusieurs plats sans duplication.',
      ],
      bulletPoints: [
        { title: 'Catégories et Ordre', desc: 'Créez et organisez vos catégories avec photos et descriptions grâce aux flèches haut/bas.' },
        { title: 'Produits et Modificateurs', desc: 'Définissez prix, photos, allergènes, ingrédients de base retirables et règles de sélection min/max.' },
        { title: '⭐ Bouton Promo Économiseur', desc: 'Situé à côté de « Dupliquer » et « Modifier », le bouton ⭐ Promo sélectionne les plats vedettes qui défileront sur l’économiseur d’écran.' },
        { title: 'Interrupteur Rapide Épuisé', desc: 'Désactivez temporairement un produit ou ingrédient en rupture d’un simple clic pour bloquer les commandes.' },
      ],
      tip: 'Créez d’abord vos collections dans l’onglet Ingrédients avant de les associer aux produits pour garantir l’homogénéité du menu.',
    },
    {
      id: 'ch4_kds_kitchen',
      icon: 'flame',
      title: '4. Écran des Commandes Cuisine (KDS)',
      subtitle: 'Organisation des cuisiniers, suivi des temps et réinitialisation de service',
      badge: 'CUISINE KDS',
      paragraphs: [
        'Le KDS remplace les bons papier par un tableau numérique interactif qui met en valeur les personnalisations et notes spéciales des clients.',
      ],
      bulletPoints: [
        { title: '🟡 À Préparer (Jaune)', desc: 'Réception immédiate du ticket avec heure exacte, type de consommation et modifications d’ingrédients surlignées.' },
        { title: '🔵 En Préparation (Bleu)', desc: 'L’équipe cuisine clique sur « Commencer » pour lancer la préparation et mesurer les temps d’attente.' },
        { title: '🟢 Prêt (Vert)', desc: 'La commande est terminée et prête pour le retrait par le client ou le service en salle.' },
        { title: '⚪ Réinitialisation Fin de Service', desc: '« Réinitialiser numérotation et commandes » remet le compteur à #1 et archive les commandes terminées.' },
      ],
      tip: 'Si la cuisine n’utilise pas de tablette dédiée, désactivez l’écran cuisine dans Paramètres : l’impression continuera de fonctionner.',
    },
    {
      id: 'ch5_printers',
      icon: 'print',
      title: '5. Imprimantes Thermiques ESC/POS, Sauvegarde & Restauration',
      subtitle: 'Configuration Bluetooth, Réseau LAN, format papier et archives ZIP',
      badge: 'MATÉRIEL & SAUVEGARDE',
      paragraphs: [
        'Compatible avec les imprimantes thermiques ESC/POS 58mm et 80mm (Bluetooth Classic/BLE ou Réseau LAN port 9100).',
        'Toute la configuration, les photos et la carte peuvent être exportées dans une archive ZIP pour transfert rapide ou sauvegarde.',
      ],
      bulletPoints: [
        { title: 'Séparation Caisse & Cuisine', desc: 'Affectez une imprimante pour les reçus clients et une autre pour les bons de préparation cuisine.' },
        { title: 'Format Papier & Impression Auto', desc: 'Sélectionnez 58mm ou 80mm et activez l’impression automatique lors de la validation du panier.' },
        { title: 'Exporter Sauvegarde ZIP', desc: 'Générez une archive complète de votre menu et de vos paramètres à conserver sur clé USB ou cloud.' },
        { title: 'Importer Sauvegarde ZIP', desc: 'Restaurez votre configuration sur une nouvelle tablette en quelques secondes via le fichier ZIP.' },
      ],
      tip: 'Effectuez toujours une impression de test depuis Paramètres avant le début du service.',
    },
    {
      id: 'ch6_kiosk_lockdown',
      icon: 'shield-checkmark',
      title: '6. Mode Borne Protégée, Kiosque & Sécurité',
      subtitle: 'Plein écran immersif, LockTask, geste des 7 pressions et code PIN',
      badge: 'SÉCURITÉ',
      paragraphs: [
        'Pour éviter toute manipulation non autorisée lorsque la tablette est en libre-service, Totem QuickBite intègre des sécurités kiosque éprouvées.',
      ],
      bulletPoints: [
        { title: 'Mode Borne Protégée (Kiosque + Plein écran)', desc: 'Interrupteur principal qui masque les barres d’état et de navigation Android.' },
        { title: 'Geste Secret de Déverrouillage (7 Touches)', desc: 'Appuyez 7 fois rapidement dans le coin supérieur droit de l’accueil pour ouvrir le pavé PIN administrateur.' },
        { title: 'Identifiants Administrateur Sécurisés', desc: 'Personnalisez Identifiant, Mot de passe et code PIN dans Paramètres ; les données sont chiffrées.' },
        { title: 'Économiseur & Économie d’Énergie', desc: 'Réglez le délai d’inactivité pour lancer le carrousel promotionnel (plats ⭐ Promo) ou l’assombrissement nocturne.' },
      ],
      tip: 'Sur les tablettes Android dédiées, définissez l’application comme « Application d’accueil par défaut » pour le démarrage automatique.',
    },
    {
      id: 'ch7_remote_web',
      icon: 'globe',
      title: '7. Panneau Distant sur Réseau Local (LAN / Web)',
      subtitle: 'Gestion sans fil en temps réel depuis smartphone, tablette ou PC',
      badge: 'CONTRÔLE DISTANT',
      paragraphs: [
        'La borne héberge un serveur web local permettant au responsable de gérer l’établissement sans déranger les clients en train de commander.',
      ],
      bulletPoints: [
        { title: 'Accès Immédiat par QR Code', desc: 'Scannez le QR Code dans les Paramètres avec l’appareil photo du smartphone pour ouvrir l’interface web.' },
        { title: 'Synchronisation Bidirectionnelle', desc: 'Toute modification de prix ou de plat effectuée sur le téléphone s’applique instantanément à la borne.' },
        { title: 'Sécurité Réseau Local', desc: 'Protégé par jeton de session et code PIN ; les flux restent cantonnés au Wi-Fi privé de l’établissement.' },
        { title: 'Zéro Dépendance au Cloud', desc: 'Fonctionne intégralement sur le serveur interne de la borne, même sans accès Internet.' },
      ],
      tip: 'Ajoutez l’adresse web à l’écran d’accueil de votre smartphone pour un accès en un clic.',
    },
    {
      id: 'ch8_licensing',
      icon: 'ribbon',
      title: '8. Licence, Mises à Jour Google Play (AAB / APK) & Maintenance',
      subtitle: 'Gestion des abonnements, validation et distribution des versions de production',
      badge: 'LICENCE & MISES À JOUR',
      paragraphs: [
        'Totem QuickBite est conçu pour la publication officielle sur Google Play Store au format AAB et supporte la génération d’APK Universal pour les bornes industrielles.',
      ],
      bulletPoints: [
        { title: 'Abonnements Officiels Google Play', desc: 'Abonnements mensuels et annuels facturés en toute sécurité via votre compte Google Play.' },
        { title: 'Vérifier & Restaurer l’Abonnement', desc: 'Le bouton « Vérifier et restaurer l’abonnement » réactive vos droits sur tout nouvel appareil.' },
        { title: 'Mises à Jour Officielles', desc: 'Distribution assurée via Google Play Store pour une stabilité et une sécurité optimales.' },
        { title: 'Pipeline Double CI/CD (GitHub Actions)', desc: 'Production automatisée de l’AAB signé pour le Play Store et de l’APK Universel pour les tests et le déploiement direct.' },
      ],
      tip: 'Conservez toujours une copie de sauvegarde ZIP avant d’effectuer des mises à jour majeures d’Android.',
    },
    {
      id: 'ch9_compliance_privacy',
      icon: 'shield-checkmark',
      title: '9. Conformité Réglementaire, RGPD & Confidentialité',
      subtitle: 'Données 100% locales, zéro profilage client et conformité de service',
      badge: 'CONFORMITÉ & RGPD',
      paragraphs: [
        'Conçu selon les principes de Privacy by Design du RGPD européen (UE 2016/679).',
        'Fonctionnement entièrement local : aucune donnée personnelle collectée ni envoyée à des tiers.',
      ],
      bulletPoints: [
        { title: '🔒 Aucune Donnée Personnelle Conservée', desc: 'Pas de saisie ni de stockage de noms, numéros de téléphone ou coordonnées bancaires.' },
        { title: '🛡️ Purge Automatique de Session', desc: 'À la fin de la commande ou après inactivité, le panier et la langue temporaire sont effacés immédiatement.' },
        { title: '🧾 Bons de Préparation & Caisse Fiscale', desc: 'Les tickets borne constituent des bons de service internes ; la facture fiscale définitive est émise par la caisse enregistreuse agréée.' },
        { title: '♿ Accessibilité Tactile', desc: 'Boutons à fort contraste (>48px) et navigation simplifiée en 5 langues.' },
      ],
      tip: 'Toutes les données du catalogue restent stockées sur la mémoire interne protégée de l’appareil.',
    },
    {
      id: 'ch10_multi_totem_printers',
      icon: 'layers',
      title: '10. Architecture Multi-Bornes, Maître/Satellite & Multi-Imprimantes par Département',
      subtitle: 'Réseau multi-postes, licence Google Play centralisée, imprimantes et KDS illimités',
      badge: 'MULTI-BORNES & MATÉRIEL',
      paragraphs: [
        'Totem QuickBite prend en charge les installations Mono-Borne ainsi que les architectures Multi-Bornes en réseau local Maître/Satellite.',
        'Tous les appareils utilisent la même application : l’abonnement Google Play Store est géré exclusivement sur la Borne Maître, tandis que les Bornes Satellites illimitées s’y connectent via le réseau Wi-Fi local sans surcoût.',
      ],
      bulletPoints: [
        { title: '👑 Borne Maître (Serveur LAN)', desc: 'Détient la licence Google Play active et coordonne la carte, les tarifs et la numérotation unifiée des commandes.' },
        { title: '🛰️ Bornes Satellites Illimitées', desc: 'Postes de commande supplémentaires pour fluidifier les heures de pointe. Les satellites synchronisent le catalogue en direct depuis le Maître.' },
        { title: '🖨️ Multi-Imprimantes par Département', desc: 'Installez autant d’imprimantes thermiques que nécessaire (Cuisine Chaude, Pizzeria, Bar, Caisse). Associez chaque catégorie de produits à son imprimante dédiée.' },
        { title: '📺 Écrans KDS Multi-Postes Miroirs', desc: 'Les écrans de cuisine reflètent exactement les départements d’impression : les barmen et cuisiniers ne voient que leurs articles respectifs.' },
        { title: '🔍 Détection Automatique LAN & Synchronisation', desc: 'Les bornes satellites détectent instantanément le Maître sur le réseau Wi-Fi avec la recherche automatique.' },
      ],
      tip: 'Attribuez un préfixe unique à chaque borne (ex. T1- et T2-) pour identifier immédiatement le point de commande.',
    },
    {
      id: 'ch11_kds_routing',
      icon: 'restaurant',
      title: '11. Routage Multi-Imprimante & Catégories KDS',
      subtitle: 'Gestion avancée des commandes divisées par département et imprimantes Bluetooth.',
      badge: 'AVANCÉ',
      paragraphs: [
        'La plateforme prend en charge l\'assignation directe de catégories (ex. Pizzas, Boissons) à des écrans KDS spécifiques et à des imprimantes Bluetooth.',
        'Allez dans l\'onglet Paramètres -> Impression du Totem pour détecter et coupler plusieurs imprimantes Bluetooth.',
        'Pour chaque imprimante ou moniteur KDS, sélectionnez les catégories dont il s\'occupe. Les commandes seront automatiquement divisées et envoyées aux bons départements.'
      ],
      tip: 'Astuce : Si vous ne sélectionnez aucune catégorie, l\'imprimante ou le KDS recevra l\'ensemble de la commande globale.'
    },
  ],

  de: [
    {
      id: 'ch1_overview',
      icon: 'restaurant',
      title: '1. Übersicht & Systemarchitektur',
      subtitle: 'Kundenterminal, Küchen-KDS, Thermodrucker und Fernverwaltung',
      badge: 'ARCHITEKTUR',
      paragraphs: [
        'Totem QuickBite ist eine ganzheitliche Self-Service-Plattform für die Gastronomie mit strikter Local-First-Architektur.',
        'Sämtliche Daten, Menüstrukturen und Betriebsfunktionen laufen im lokalen Netzwerk (LAN/WLAN) des Betriebs – volle Einsatzbereitschaft auch bei Internetausfall.',
      ],
      bulletPoints: [
        { title: '📱 Touchscreen-Kundenterminal', desc: 'Intuitive Benutzeroberfläche für eigenständige Kundenbestellungen oder Ausgabe von Wartenummern für die Kasse.' },
        { title: '🍳 Digitales Küchen-KDS', desc: 'Echtzeit-Bestellanzeige mit Arbeitsstatus (Zu vorbereiten, In Vorbereitung, Bereit, Abgeschlossen).' },
        { title: '🖨️ ESC/POS-Thermodrucker', desc: 'Automatischer Druck von Kundenbelegen und getrennten Küchenbons (Bluetooth und LAN-Netzwerk).' },
        { title: '🌐 LAN & Web-Fernbedienfeld', desc: 'Verwaltung von Speisen, Preisen, Ausverkäufen und Fotos über jedes Smartphone oder PC im selben WLAN.' },
      ],
      tip: 'Verbinden Sie Terminal, Küchen-Tablet, Netzwerkdrucker und Verwaltungsgeräte mit demselben Betriebs-WLAN für verzögerungsfreie Synchronisierung.',
    },
    {
      id: 'ch2_customer_flow',
      icon: 'people',
      title: '2. Kundenablauf & Sprachauswahl',
      subtitle: 'Vom Startbildschirm über die Individualisierung bis zur Belegabholung',
      badge: 'KUNDE',
      paragraphs: [
        'Die Benutzeroberfläche verkürzt Wartezeiten und vermeidet Missverständnisse. Das System bietet sofortige Unterstützung für 5 Sprachen (Italiano, English, Español, Français, Deutsch).',
        'Die Sprachauswahl des Kunden am Startbildschirm gilt ausschließlich für die aktuelle Bestellsitzung und verändert nicht die Verwaltungssprache.',
      ],
      bulletPoints: [
        { title: '1. Modus & Sprachwahl', desc: 'Der Kunde wählt seine Sprache und entscheidet sich für „Am Terminal bestellen“ oder „Nur Wartenummer ziehen“.' },
        { title: '2. Speisekarte durchstöbern', desc: 'Kategorien mit hochauflösenden Fotos, Preisen, Beschreibungen und klar ausgewiesenen Allergenen.' },
        { title: '3. Gerichte anpassen', desc: 'Zutaten abwählen („Ohne Zwiebeln“), Extras hinzufügen („Extra Käse“) und Pflicht-/Kombiauswahlen treffen.' },
        { title: '4. Verzehrart & Bezahlung', desc: 'Auswahl zwischen „Hier essen“ oder „Zum Mitnehmen“ und Festlegung der Zahlungsart.' },
        { title: '5. Beleg & Abholung', desc: 'Ausgabe der fortlaufenden Bestellnummer mit Kundenbeleg und sofortige Weiterleitung an die Küche.' },
      ],
      tip: 'Der Warenkorb wird nach der eingestellten Inaktivitätszeit (Standard 60s) automatisch geleert, um den Datenschutz zu wahren.',
    },
    {
      id: 'ch3_menu_management',
      icon: 'fast-food',
      title: '3. Menüverwaltung, Zutaten & ⭐ Promo-Bildschirmschoner',
      subtitle: 'Katalog, wiederverwendbare Bibliotheken, Varianten und Werbefläche',
      badge: 'KATALOG',
      paragraphs: [
        'Über den Admin-Bereich oder das Web-Fernbedienfeld können Sie die Speisekarte in Echtzeit aktualisieren und Werbebanner konfigurieren.',
        'Unter Zutaten erstellen Sie globale Sammlungen (Saucen, Extras), die sich ohne doppelte Eingabe mit mehreren Produkten verknüpfen lassen.',
      ],
      bulletPoints: [
        { title: 'Kategorien & Reihenfolge', desc: 'Erstellen und sortieren Sie Kategorien mit Bildern und Texten über Auf-/Ab-Pfeile.' },
        { title: 'Produkte & Modifikatoren', desc: 'Preise, Bilder, Allergene, abwählbare Zutaten und Auswahlregeln mit Min-/Max-Grenzen definieren.' },
        { title: '⭐ Promo-Schaltfläche', desc: 'Neben „Duplizieren“ und „Bearbeiten“ markiert die Taste ⭐ Promo Highlight-Gerichte für den Bildschirmschoner-Karussellaufruf im Ruhezustand.' },
        { title: 'Schneller Ausverkauft-Schalter', desc: 'Ausverkaufte Produkte oder Zutaten mit einem Tippen sperren, um Fehlbestellungen sofort zu verhindern.' },
      ],
      tip: 'Erstellen Sie Sammlungen zuerst in der Registerkarte Zutaten und verknüpfen Sie diese anschließend mit Produkten.',
    },
    {
      id: 'ch4_kds_kitchen',
      icon: 'flame',
      title: '4. Küchenbestellanzeige (KDS)',
      subtitle: 'Abläufe für Köche, Zeitüberwachung und Schichtabschluss-Reset',
      badge: 'KÜCHE KDS',
      paragraphs: [
        'Das KDS ersetzt Papierbons durch ein übersichtliches digitales Board, das Kundenwünsche und Extranotizen deutlich hervorhebt.',
      ],
      bulletPoints: [
        { title: '🟡 Zu Vorbereiten (Gelb)', desc: 'Sofortiger Eingang des Bons vom Terminal mit Uhrzeit, Verzehrart und markierten Zutatenänderungen.' },
        { title: '🔵 In Vorbereitung (Blau)', desc: 'Das Küchenteam tippt auf „Start“, um die Zubereitung zu beginnen und Zeiten zu kontrollieren.' },
        { title: '🟢 Bereit (Grün)', desc: 'Die Bestellung ist fertiggestellt und bereit zur Übergabe an den Kunden.' },
        { title: '⚪ Reset & Schichtende', desc: '„Nummerierung und Bestellungen zurücksetzen“ setzt den Zähler auf #1 und archiviert abgeschlossene Bons.' },
      ],
      tip: 'Falls die Küche kein eigenes Tablet nutzt, deaktivieren Sie die Küchenanzeige in den Einstellungen: Belegdrucke laufen uneingeschränkt weiter.',
    },
    {
      id: 'ch5_printers',
      icon: 'print',
      title: '5. ESC/POS-Thermodrucker, ZIP-Sicherung & Wiederherstellung',
      subtitle: 'Bluetooth- und LAN-Einrichtung, Papierbreite und portable ZIP-Archive',
      badge: 'HARDWARE & SICHERUNG',
      paragraphs: [
        'Unterstützt Standard-ESC/POS-Thermodrucker (58mm und 80mm) über Bluetooth Classic/BLE oder LAN-Netzwerk (Port 9100).',
        'Alle Einstellungen, Bilder und Speisen können als ZIP-Datei für schnelle Gerätewechsel exportiert werden.',
      ],
      bulletPoints: [
        { title: 'Getrennte Kassen- & Küchendrucker', desc: 'Weisen Sie separate Drucker für Kundenquittungen und Küchenzubereitungsbons zu.' },
        { title: 'Papierbreite & Automatischer Druck', desc: '58mm oder 80mm wählen und automatischen Küchendruck bei Bestellabschluss aktivieren.' },
        { title: 'ZIP-Sicherung Exportieren', desc: 'Erstellen Sie ein vollständiges Archiv Ihres Katalogs und speichern Sie es auf USB oder Cloud.' },
        { title: 'ZIP-Sicherung Importieren', desc: 'Stellen Sie Ihre Restaurantkonfiguration auf jedem Ersatztablet in Sekundenschnelle wieder her.' },
      ],
      tip: 'Führen Sie vor dem Service immer einen Testdruck in den Einstellungen durch.',
    },
    {
      id: 'ch6_kiosk_lockdown',
      icon: 'shield-checkmark',
      title: '6. Geschützter Totem-Modus, Kiosk-Sperre & Sicherheit',
      subtitle: 'Vollbildmodus, LockTask, 7-Tipp-Geste und PIN-Schutz',
      badge: 'SICHERHEIT',
      paragraphs: [
        'Um Manipulationen am öffentlich aufgestellten Tablet zu verhindern, verfügt Totem QuickBite über umfassende Kiosk-Sicherheitsfunktionen.',
      ],
      bulletPoints: [
        { title: 'Geschützter Totem-Modus (Kiosk + Vollbild)', desc: 'Zentraler Schalter, der Status- und Navigationsleisten von Android ausblendet.' },
        { title: 'Geheime Entsperrgeste (7 Berührungen)', desc: 'Tippen Sie 7 Mal schnell oben rechts auf den Startbildschirm, um das PIN-Feld aufzurufen.' },
        { title: 'Sichere Administrator-Zugangsdaten', desc: 'Benutzername, Passwort und PIN in Einstellungen festlegen; Daten werden verschlüsselt gespeichert.' },
        { title: 'Bildschirmschoner & Energie sparen', desc: 'Inaktivitäts-Timeout für das Promo-Karussell (mit ⭐ Promo markierte Artikel) oder Nacht-Dimmung einstellen.' },
      ],
      tip: 'Legen Sie die App in Android als „Standard-Start-App“ fest, um den automatischen Start beim Einschalten zu gewährleisten.',
    },
    {
      id: 'ch7_remote_web',
      icon: 'globe',
      title: '7. Fernbedienfeld im lokalen Netzwerk (LAN / Web)',
      subtitle: 'Kabellose Echtzeit-Verwaltung von Smartphone, Tablet oder PC',
      badge: 'FERNBEDIENUNG',
      paragraphs: [
        'Das Terminal verfügt über einen integrierten lokalen Webserver, über den Sie Anpassungen vornehmen können, ohne den Kundenbetrieb zu unterbrechen.',
      ],
      bulletPoints: [
        { title: 'Sofortzugriff per QR-Code', desc: 'Scannen Sie den QR-Code in den Terminal-Einstellungen mit dem Handy, um das Web-Panel zu öffnen.' },
        { title: 'Echtzeit-Synchronisierung', desc: 'Preis- oder Menüänderungen vom Smartphone erscheinen sofort auf dem Terminal-Bildschirm.' },
        { title: 'Lokale Netzwerksicherheit', desc: 'Geschützt durch Sitzungstoken und PIN; Datenverkehr bleibt ausschließlich im Betriebs-WLAN.' },
        { title: 'Keine Cloud-Abhängigkeit', desc: 'Läuft vollständig über den internen Server des Terminals, auch ohne Internetverbindung.' },
      ],
      tip: 'Speichern Sie die Webadresse als Lesezeichen auf Ihrem Smartphone für den Schnellzugriff.',
    },
    {
      id: 'ch8_licensing',
      icon: 'ribbon',
      title: '8. Lizenz, Google Play Updates (AAB / APK) & Wartung',
      subtitle: 'Abonnementverwaltung, Store-Prüfung und Bereitstellung von Produktions-Builds',
      badge: 'LIZENZ & UPDATES',
      paragraphs: [
        'Totem QuickBite ist für die Google Play Store-Veröffentlichung via AAB optimiert und unterstützt universelle APK-Builds für Industrie-Kiosk-Hardware.',
      ],
      bulletPoints: [
        { title: 'Offizielle Google Play Abonnements', desc: 'Monatliche und jährliche Tarife, sicher abgerechnet über Ihr Google Play-Konto.' },
        { title: 'Abonnement Prüfen & Wiederherstellen', desc: '„Google Play-Abonnement prüfen & wiederherstellen“ reaktiviert Ihre Lizenz bei Gerätewechsel.' },
        { title: 'Offizielle Update-Kanäle', desc: 'Verteilung über den Google Play Store für maximale Zuverlässigkeit und Sicherheit.' },
        { title: 'Duale CI/CD-Pipeline (GitHub Actions)', desc: 'Automatische Erstellung von signiertem AAB für den Play Store und Universal-APK für manuelle Installation.' },
      ],
      tip: 'Erstellen Sie vor großen Android-Systemupdates immer eine vollständige ZIP-Sicherung.',
    },
    {
      id: 'ch9_compliance_privacy',
      icon: 'shield-checkmark',
      title: '9. Rechtliche Konformität, DSGVO & Datenschutz',
      subtitle: 'Lokale Datenspeicherung, kein Kunden-Tracking und Kassenkonformität',
      badge: 'DSGVO & DATENSCHUTZ',
      paragraphs: [
        'Entwickelt nach den Grundsätzen von Privacy by Design gemäß EU-DSGVO (2016/679).',
        'Vollständig lokaler Betrieb: keine Erfassung privater Daten und keine Weitergabe an Dritte.',
      ],
      bulletPoints: [
        { title: '🔒 Keine Speicherung von Kundendaten', desc: 'Es werden weder Namen, Telefonnummern noch Kreditkartendaten erfasst.' },
        { title: '🛡️ Automatische Sitzungsbereinigung', desc: 'Nach Abschluss der Bestellung oder bei Inaktivität werden Warenkorb und temporäre Sprache gelöscht.' },
        { title: '🧾 Vorbereitungsscheine & Kassenkonformität', desc: 'Gedruckte Scheine dienen als Zubereitungsbeleg; die fiskalische Erfassung erfolgt an der Hauptkasse.' },
        { title: '♿ Touch-Barrierefreiheit', desc: 'Kontrastreiche Schaltflächen (>48px) und einfache 5-Sprachen-Auswahl.' },
      ],
      tip: 'Alle Speisekarten- und Einstellungsdaten verbleiben geschützt im lokalen Gerätespeicher.',
    },
    {
      id: 'ch10_multi_totem_printers',
      icon: 'layers',
      title: '10. Multi-Terminal-Architektur, Master/Satellit & Abteilungs-Thermodrucker',
      subtitle: 'Multi-Kiosk-Netzwerk, zentrale Google Play-Lizenz, unbegrenzte Drucker & KDS-Displays',
      badge: 'MULTI-TERMINAL & HARDWARE',
      paragraphs: [
        'Totem QuickBite unterstützt sowohl Einzelterminal- (Standalone) als auch Multi-Terminal-Netzwerke (Master/Satellit über lokales WLAN/LAN).',
        'Alle Stationen verwenden dieselbe App: Das Google Play-Abonnement wird ausschließlich auf dem Master-Terminal verwaltet. Unbegrenzte Satelliten-Terminals verbinden sich lokal im Netzwerk und übernehmen Menü, Lizenzstatus und Bestellnummern verzögerungsfrei.',
      ],
      bulletPoints: [
        { title: '👑 Master-Terminal (LAN-Server)', desc: 'Verwaltet die Google Play-Lizenz und synchronisiert Speisekarte, Preise und einheitliche Bestellnummern im gesamten Betrieb.' },
        { title: '🛰️ Unbegrenzte Satelliten-Terminals', desc: 'Zusätzliche Kiosks zur Vermeidung von Warteschlangen. Satelliten rufen Katalogdaten live vom Master ab und leiten Bestellungen lokal weiter.' },
        { title: '🖨️ Unbegrenzte Abteilungsdrucker', desc: 'Binden Sie Thermodrucker für Küche, Pizzaofen, Bar und Kassenbelege ein. Weisen Sie jeder Druckstation spezifische Produktkategorien zu.' },
        { title: '📺 Gespiegelte Abteilungs-KDS-Displays', desc: 'Küchenbildschirme spiegeln die Druckerabteilungen wider: Pizzaköche, Köche und Barkeeper sehen nur die für sie relevanten Artikel.' },
        { title: '🔍 Automatische LAN-Erkennung & 1-Klick-Sync', desc: 'Satelliten-Terminals finden den Master im lokalen WLAN automatisch über die Suchfunktion.' },
      ],
      tip: 'Vergeben Sie für jedes Terminal ein eindeutiges Präfix (z. B. T1- und T2-), um den Bestellort sofort zuzuordnen.',
    },
    {
      id: 'ch11_kds_routing',
      icon: 'restaurant',
      title: '11. Multi-Drucker-Routing & KDS-Kategorien',
      subtitle: 'Erweiterte Bestellverwaltung unterteilt nach Abteilungen und Bluetooth-Druckern.',
      badge: 'FORTGESCHRITTEN',
      paragraphs: [
        'Die Plattform unterstützt die direkte Zuweisung von Kategorien (z.B. Pizzen, Getränke) an spezifische KDS-Bildschirme und Bluetooth-Drucker.',
        'Gehen Sie auf die Registerkarte Einstellungen -> Drucken am Totem, um mehrere Bluetooth-Drucker zu erkennen und zu koppeln.',
        'Wählen Sie für jeden Drucker oder KDS-Monitor die zuständigen Kategorien aus. Die Bestellungen werden automatisch aufgeteilt und an die richtigen Abteilungen gesendet.'
      ],
      tip: 'Tipp: Wenn Sie keine Kategorie auswählen, empfängt der Drucker oder KDS die gesamte globale Bestellung.'
    },
  ],
};
