#!/usr/bin/env python3
import sys
import os

def generate(token="", repo="Jonnymago/totem", commit_sha=""):
    print(f"[1/2] Generating optimized multi-arch Kaggle build script for {repo}...")

    script_content = f'''#!/usr/bin/env python3
# Auto-generated by CI/CD GitHub Action for Multi-Arch Kaggle APK Build
import os
import sys
import glob
import subprocess
import shutil

REPO_URL = "https://x-access-token:{token}@github.com/{repo}.git" if "{token}" else "https://github.com/{repo}.git"
COMMIT_SHA = "{commit_sha}"
PROJECT_DIR = "/kaggle/working/app_project"

def run_cmd(cmd, cwd=None, check=True):
    print(f"\\n>> Executing: {{cmd}} (cwd: {{cwd or '.'}})")
    res = subprocess.run(cmd, shell=True, cwd=cwd)
    if check and res.returncode != 0:
        print(f"❌ Command failed with exit code {{res.returncode}}")
        sys.exit(res.returncode)
    return res

def main():
    print("==================================================")
    print("📦 [1/4] Estrazione e preparazione sorgenti...")
    print("==================================================")
    if os.path.exists(PROJECT_DIR):
        shutil.rmtree(PROJECT_DIR)
    
    run_cmd(f"git clone --depth 1 {{REPO_URL}} {{PROJECT_DIR}}")
    os.chdir(PROJECT_DIR)
    print(f"✅ Sorgenti preparate in {{PROJECT_DIR}}")

    print("==================================================")
    print("⚡ [2/4] Setup Java & Android SDK Cache / Fallback...")
    print("==================================================")
    run_cmd("apt-get update -qq && apt-get install -y -qq openjdk-17-jdk unzip wget curl > /dev/null 2>&1", check=False)
    os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-17-openjdk-amd64"
    os.environ["PATH"] = f"{{os.environ.get('JAVA_HOME', '')}}/bin:" + os.environ.get("PATH", "")

    CACHE_SDK_PATHS = [
        "/kaggle/input/android-sdk-cache/android-sdk",
        "/kaggle/input/android-sdk-cache"
    ]
    CACHE_SDK = None
    for p in CACHE_SDK_PATHS:
        if os.path.exists(os.path.join(p, "platforms")) or os.path.exists(os.path.join(p, "platform-tools")):
            CACHE_SDK = p
            break

    WORK_SDK = "/kaggle/working/android-sdk"

    if CACHE_SDK and os.path.exists(CACHE_SDK):
        print(f"🚀 Utilizzo Android SDK pre-caricato da Cache ({{CACHE_SDK}})...")
        os.environ["ANDROID_HOME"] = CACHE_SDK
        os.environ["ANDROID_SDK_ROOT"] = CACHE_SDK
        os.environ["PATH"] += f":{{CACHE_SDK}}/cmdline-tools/latest/bin:{{CACHE_SDK}}/platform-tools"
    else:
        print("⚠️ Cache non rilevata: installazione SDK da zero...")
        sdk_path = WORK_SDK
        cmd_tools_dir = f"{{sdk_path}}/cmdline-tools/latest/bin"
        os.environ["ANDROID_HOME"] = sdk_path
        os.environ["ANDROID_SDK_ROOT"] = sdk_path
        os.environ["PATH"] += f":{{cmd_tools_dir}}:{{sdk_path}}/platform-tools"
        
        if not os.path.exists(f"{{cmd_tools_dir}}/sdkmanager"):
            os.makedirs(f"{{sdk_path}}/cmdline-tools", exist_ok=True)
            run_cmd("wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O /tmp/cmdline.zip")
            run_cmd(f"unzip -q -o /tmp/cmdline.zip -d {{sdk_path}}/cmdline-tools")
            run_cmd(f"rm -rf {{sdk_path}}/cmdline-tools/latest 2>/dev/null || true", check=False)
            run_cmd(f"mv {{sdk_path}}/cmdline-tools/cmdline-tools {{sdk_path}}/cmdline-tools/latest", check=False)
            run_cmd(f"yes | {{cmd_tools_dir}}/sdkmanager --licenses > /dev/null 2>&1", check=False)
            run_cmd(f"{{cmd_tools_dir}}/sdkmanager 'platform-tools' 'platforms;android-34' 'build-tools;34.0.0' > /dev/null 2>&1", check=False)

    print("==================================================")
    print("🔨 [3/4] Compilazione Gradle Multi-Arch (arm64-v8a, armeabi-v7a, x86_64)...")
    print("==================================================")
    frontend_dir = os.path.join(PROJECT_DIR, "frontend")
    gradle_target_dir = PROJECT_DIR

    if os.path.exists(frontend_dir):
        print("📦 Setup dipendenze e prebuild Expo in frontend/...")
        run_cmd("npm install --legacy-peer-deps", cwd=frontend_dir)
        run_cmd("npx expo prebuild --platform android --clean", cwd=frontend_dir)
        android_dir = os.path.join(frontend_dir, "android")
        if os.path.exists(android_dir):
            gradle_target_dir = android_dir

    os.chdir(gradle_target_dir)
    run_cmd("chmod +x ./gradlew")

    # Compilazione mirata per ARM + FydeOS (escluso x86 32-bit per ottimizzare tempi C++)
    gradle_cmd = (
        "./gradlew assembleDebug "
        "-Pandroid.injected.build.abi=arm64-v8a,armeabi-v7a,x86_64 "
        "--no-daemon "
        "--parallel "
        "--max-workers=4 "
        "-Dorg.gradle.jvmargs='-Xmx8g -XX:+UseParallelGC'"
    )
    build_res = subprocess.run(gradle_cmd, shell=True, cwd=gradle_target_dir)

    print("==================================================")
    print("📤 [4/4] Finalizzazione APK Output...")
    print("==================================================")
    apks = glob.glob(f"{{PROJECT_DIR}}/**/build/outputs/apk/**/*.apk", recursive=True)
    if not apks:
        apks = glob.glob(f"/kaggle/working/**/*.apk", recursive=True)

    if apks and build_res.returncode == 0:
        target_output = "/kaggle/working/app-debug.apk"
        shutil.copy2(apks[0], target_output)
        size_mb = os.path.getsize(target_output) / (1024 * 1024)
        print(f"✅ APK pronto per il download: {{target_output}} ({{size_mb:.2f}} MB)")
    else:
        print("❌ Errore durante la compilazione Gradle.")
        sys.exit(1)

    print("🎉 Build completata con successo!")

if __name__ == "__main__":
    main()
'''

    with open("kaggle_build.py", "w", encoding="utf-8") as f:
        f.write(script_content)

    file_size_kb = os.path.getsize("kaggle_build.py") / 1024
    print(f"[2/2] kaggle_build.py generated successfully (Size: {file_size_kb:.2f} KB < 1024 KB limit).")

if __name__ == "__main__":
    token = sys.argv[1] if len(sys.argv) > 1 else ""
    repo = sys.argv[2] if len(sys.argv) > 2 else "Jonnymago/totem"
    commit_sha = sys.argv[3] if len(sys.argv) > 3 else ""
    generate(token, repo, commit_sha)
