#!/usr/bin/env python3
import os
import sys
import tarfile
import io
import base64

def generate():
    print("[1/3] Packing repository into in-memory compressed archive...")
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w:gz") as tar:
        for root, dirs, files in os.walk("."):
            dirs[:] = [d for d in dirs if d not in [".git", "node_modules", ".gradle", "build", "dist", ".expo", ".idea"]]
            for file in files:
                if file in ["kaggle_build.py", "dist.zip"]:
                    continue
                full_path = os.path.join(root, file)
                arc_name = os.path.relpath(full_path, ".")
                tar.add(full_path, arcname=arc_name)

    payload_b64 = base64.b64encode(buf.getvalue()).decode("ascii")
    print(f"[2/3] Payload compressed size: {len(buf.getvalue()) / 1024:.1f} KB (base64: {len(payload_b64) / 1024:.1f} KB)")

    script_template = '''#!/usr/bin/env python3
# Auto-generated by CI/CD GitHub Action for Kaggle APK Build
import os
import sys
import subprocess
import base64
import io
import tarfile
import shutil

PAYLOAD_B64 = """__PAYLOAD_PLACEHOLDER__"""

def main():
    print("==================================================")
    print("🚀 [1/6] Unpacking Repository Payload...")
    print("==================================================")
    payload_bytes = base64.b64decode(PAYLOAD_B64)
    target_dir = "/kaggle/working/totem_src"
    os.makedirs(target_dir, exist_ok=True)
    with tarfile.open(fileobj=io.BytesIO(payload_bytes), mode="r:gz") as tar:
        tar.extractall(target_dir)

    os.chdir(target_dir)
    print(f"✅ Workspace ready at {target_dir}")

    print("==================================================")
    print("☕ [2/6] Setting up OpenJDK 17...")
    print("==================================================")
    subprocess.run("sudo apt-get update -qq && sudo apt-get install -y -qq openjdk-17-jdk wget unzip curl", shell=True, check=False)
    os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-17-openjdk-amd64"
    os.environ["PATH"] = f"{os.environ.get('JAVA_HOME', '')}/bin:" + os.environ.get("PATH", "")

    print("==================================================")
    print("📱 [3/6] Setting up Android SDK (Platform 34 / 35)...")
    print("==================================================")
    sdk_root = "/kaggle/working/android-sdk"
    os.environ["ANDROID_HOME"] = sdk_root
    os.environ["ANDROID_SDK_ROOT"] = sdk_root
    os.environ["PATH"] = f"{sdk_root}/cmdline-tools/latest/bin:{sdk_root}/platform-tools:" + os.environ.get("PATH", "")

    if not os.path.exists(f"{sdk_root}/cmdline-tools/latest/bin/sdkmanager"):
        os.makedirs(f"{sdk_root}/cmdline-tools", exist_ok=True)
        subprocess.run("wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O /tmp/cmdtools.zip", shell=True, check=True)
        subprocess.run(f"unzip -q /tmp/cmdtools.zip -d /tmp/cmdtools && mv /tmp/cmdtools/cmdline-tools {sdk_root}/cmdline-tools/latest", shell=True, check=True)
        subprocess.run("yes | sdkmanager --licenses > /dev/null 2>&1", shell=True, check=False)
        subprocess.run("sdkmanager 'platforms;android-34' 'platforms;android-35' 'build-tools;34.0.0' 'platform-tools' > /dev/null 2>&1", shell=True, check=False)

    print("==================================================")
    print("📦 [4/6] Installing Node Dependencies...")
    print("==================================================")
    frontend_dir = os.path.join(target_dir, "frontend")
    if os.path.exists(frontend_dir):
        os.chdir(frontend_dir)
        subprocess.run("npm install --legacy-peer-deps", shell=True, check=True)
        print("==================================================")
        print("🔨 [5/6] Generating Native Android & Building APK...")
        print("==================================================")
        subprocess.run("npx expo prebuild --platform android --clean", shell=True, check=True)
        android_dir = os.path.join(frontend_dir, "android")
        if os.path.exists(android_dir):
            os.chdir(android_dir)
            subprocess.run("chmod +x gradlew && ./gradlew assembleDebug", shell=True, check=True)
    else:
        print("Running Gradle build from workspace root...")
        subprocess.run("chmod +x gradlew && ./gradlew assembleDebug", shell=True, check=True)

    print("==================================================")
    print("📦 [6/6] Exporting Output APK Artifacts...")
    print("==================================================")
    found_apk = False
    for root, dirs, files in os.walk("/kaggle/working"):
        for file in files:
            if file.endswith(".apk"):
                src_apk = os.path.join(root, file)
                dst_apk = os.path.join("/kaggle/working", file)
                if src_apk != dst_apk:
                    shutil.copy2(src_apk, dst_apk)
                print(f"🎉 Artifact ready: {dst_apk} ({os.path.getsize(dst_apk)} bytes)")
                found_apk = True

    if not found_apk:
        print("❌ ERROR: No APK generated.")
        sys.exit(1)

    print("✅ Build completed successfully!")

if __name__ == "__main__":
    main()
'''

    final_script = script_template.replace("__PAYLOAD_PLACEHOLDER__", payload_b64)
    with open("kaggle_build.py", "w", encoding="utf-8") as f:
        f.write(final_script)

    print("[3/3] Generated kaggle_build.py successfully.")

if __name__ == "__main__":
    generate()
