#!/usr/bin/env python3
import sys
import os

def generate(token="", repo="Jonnymago/totem", commit_sha=""):
    print(f"[1/2] Generating lightweight Kaggle build script for {repo}...")

    script_content = f'''#!/usr/bin/env python3
# Auto-generated by CI/CD GitHub Action for Kaggle APK Build
import os
import sys
import subprocess
import shutil

REPO_URL = "https://x-access-token:{token}@github.com/{repo}.git" if "{token}" else "https://github.com/{repo}.git"
COMMIT_SHA = "{commit_sha}"
TARGET_DIR = "/kaggle/working/totem_src"

def run_cmd(cmd, cwd=None, check=True):
    print(f"\\n>> Executing: {{cmd}} (cwd: {{cwd or '.'}})")
    res = subprocess.run(cmd, shell=True, cwd=cwd)
    if check and res.returncode != 0:
        print(f"❌ Command failed with exit code {{res.returncode}}")
        sys.exit(res.returncode)
    return res

def main():
    print("==================================================")
    print("🚀 [1/6] Cloning Repository...")
    print("==================================================")
    if os.path.exists(TARGET_DIR):
        shutil.rmtree(TARGET_DIR)
    
    run_cmd(f"git clone --depth 1 {{REPO_URL}} {{TARGET_DIR}}")
    os.chdir(TARGET_DIR)
    print(f"✅ Cloned successfully into {{TARGET_DIR}}")

    print("==================================================")
    print("☕ [2/6] Setting up OpenJDK 17...")
    print("==================================================")
    run_cmd("sudo apt-get update -qq && sudo apt-get install -y -qq openjdk-17-jdk wget unzip curl", check=False)
    os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-17-openjdk-amd64"
    os.environ["PATH"] = f"{{os.environ.get('JAVA_HOME', '')}}/bin:" + os.environ.get("PATH", "")

    print("==================================================")
    print("📱 [3/6] Setting up Android SDK (Platform 34 / 35)...")
    print("==================================================")
    sdk_root = "/kaggle/working/android-sdk"
    os.environ["ANDROID_HOME"] = sdk_root
    os.environ["ANDROID_SDK_ROOT"] = sdk_root
    os.environ["PATH"] = f"{{sdk_root}}/cmdline-tools/latest/bin:{{sdk_root}}/platform-tools:" + os.environ.get("PATH", "")

    if not os.path.exists(f"{{sdk_root}}/cmdline-tools/latest/bin/sdkmanager"):
        os.makedirs(f"{{sdk_root}}/cmdline-tools", exist_ok=True)
        run_cmd("wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O /tmp/cmdtools.zip")
        run_cmd(f"unzip -q /tmp/cmdtools.zip -d /tmp/cmdtools && mv /tmp/cmdtools/cmdline-tools {{sdk_root}}/cmdline-tools/latest")
        run_cmd("yes | sdkmanager --licenses > /dev/null 2>&1", check=False)
        run_cmd("sdkmanager 'platforms;android-34' 'platforms;android-35' 'build-tools;34.0.0' 'platform-tools' > /dev/null 2>&1", check=False)

    print("==================================================")
    print("📦 [4/6] Installing Node Dependencies...")
    print("==================================================")
    frontend_dir = os.path.join(TARGET_DIR, "frontend")
    if os.path.exists(frontend_dir):
        run_cmd("npm install --legacy-peer-deps", cwd=frontend_dir)
        print("==================================================")
        print("🔨 [5/6] Generating Native Android & Building APK...")
        print("==================================================")
        run_cmd("npx expo prebuild --platform android --clean", cwd=frontend_dir)
        android_dir = os.path.join(frontend_dir, "android")
        if os.path.exists(android_dir):
            run_cmd("chmod +x gradlew && ./gradlew assembleDebug", cwd=android_dir)
    else:
        print("Running Gradle build from workspace root...")
        run_cmd("chmod +x gradlew && ./gradlew assembleDebug", cwd=TARGET_DIR)

    print("==================================================")
    print("📦 [6/6] Exporting Output APK Artifacts...")
    print("==================================================")
    found_apk = False
    for root, dirs, files in os.walk("/kaggle/working"):
        for file in files:
            if file.endswith(".apk"):
                src_apk = os.path.join(root, file)
                dst_apk = os.path.join("/kaggle/working", file)
                if src_apk != dst_apk:
                    shutil.copy2(src_apk, dst_apk)
                size_mb = os.path.getsize(dst_apk) / (1024 * 1024)
                print(f"🎉 Artifact ready: {{dst_apk}} ({{size_mb:.2f}} MB)")
                found_apk = True

    if not found_apk:
        print("❌ ERROR: No APK generated.")
        sys.exit(1)

    print("✅ Build completed successfully!")

if __name__ == "__main__":
    main()
'''

    with open("kaggle_build.py", "w", encoding="utf-8") as f:
        f.write(script_content)

    file_size_kb = os.path.getsize("kaggle_build.py") / 1024
    print(f"[2/2] kaggle_build.py generated successfully (Size: {file_size_kb:.2f} KB < 1024 KB limit).")

if __name__ == "__main__":
    token = sys.argv[1] if len(sys.argv) > 1 else ""
    repo = sys.argv[2] if len(sys.argv) > 2 else "Jonnymago/totem"
    commit_sha = sys.argv[3] if len(sys.argv) > 3 else ""
    generate(token, repo, commit_sha)
